numpy/numpy-tutorials

environment.yml

This is needed for the Moore's Law tutorial by @cooperrc.

Adds statsmodels dependency.

---

requirements.txt

@melissawm, to open md as notebook the jupyter-book dependency will allow Jupyter (in a binder environment) to recognize the markdown file as a notebook.
I think this is the missing piece to work with md files exclusively.

add jupyter-book to requirements.txt

---

README.md

Updates the README with content and note about workflow changes.

---

environment.yml

Updates dependencies for the new infrastructure (note that jupyter-book is not available as a conda package, and has to be added via pip).
(I'll merge soon unless there are other considerations)

Adds jupyter-book dependency to environment.yml file.

---

.circleci/config.yml
site/requirements.txt

Set the lower bound of the dependency on MarkupSafe to v1.1 to prevent issues with dependency resolution.

Fix dependency resolution in CI

---

.circleci/config.yml
site/_templates/layout.html

Adds a `deploy-docs` job to the circleci workflow to deploy the tutorials site using `gh-pages`. The doc deployment job will only be run on a merge to master.
The missing component is the ssh fingerprint - this requires the ability to add ssh keys to both the numpy/numpy-tutorials repository on GitHub, as well as adding the private key to circleci. I have the appropriate permissions for circleci but not GitHub. Fortunately, the procedure is well-documented, just follow the instructions here: https://circleci.com/docs/2.0/gh-bb-integration/#creating-a-github-deploy-key. I tested this out on my own fork and everything went smoothly.
Note that this will deploy to the standard URL used for `gh-pages` deployments, something like https://numpy.github.io/numpy-tutorials. Changing the default URL …

CI: Set up circleci to deploy sphinx site via gh-pages

---

site/index.md

When I visit the site at numpy.org/numpy-tutorials in firefox, I get a notification in the URL bar that says: "parts of this page are not secure (such as images).
I grepped through and noticed that the binder badge was `http://`. My hypothesis is that changing these links to https may help. If anyone has any more concrete ideas of what may be causing the issue, please weigh in!

MAINT: Switch binder links to https

---

content/tutorial-deep-learning-on-mnist.md

This is an (admittedly ugly) temporary fix for the cell timeout problem. If anyone has a better solution, feel free to close this PR :)

Adds control for the execution of cell that caused timeout.

---

.circleci/config.yml
content/tutorial-style-guide.md
site/conf.py
site/index.md

Updates configuration + docs after the renaming of the default branch from master -> main.
Shouldn't be merged until after the branch renaming is done (marking as draft for now).

MAINT: changes related to default branch renaming

---

.circleci/config.yml
content/tutorial-deep-learning-on-mnist.md

Uses header spoofing to circumvent problems with downloading the MNIST digit data. Also adds data caching to the circleCI builds so in principle, the MNIST data will be cached between CI runs.
Closes #63

Fix 403 when downloading data for mnist tutorial

---

.circleci/config.yml
content/pairing.md
content/tutorial-deep-learning-on-mnist.md
content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md
requirements.txt
site/conf.py
site/index.md

This PR combines a plethora of tweaks and fixes to make the build/test/deploy infrastructure more reliable. The end result should be a reduction in CI failures due to things like resource requirements and execution timeouts.
Note this also includes some changes to the tutorials themselves, most notably the deep learning tutorials, to improve their usability in resource-constrained environments binder. Two changes to tutorial content need special attention:
1. The evaluation step of the mnist tutorial has been vectorized. This has the advantage of demonstrating vectorization, but also significantly improves run-time performance.
2. Reducing the number of episodes in the RL tutorial from 10 -> 3 (along with batch size). This is entirely a run-time argument: running the deep-rl tutorial in …

MAINT: Fix build failures and execution timeouts

---

content/tutorial-deep-learning-on-mnist.md
content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md

Updates any usage of `np.random` in the tutorials to use the newer, recommended (as of 1.17) API for the random package. This also required some rewording in the text, so please pay close attention when checking that the text changes didn't distort the original intended meaning.

Ensure all tutorials use the recommended `Generator` API for random number generation

---

apt.txt

Adds an `apt.txt` file to fix Binder configuration (installs cmake and ffmpeg needed for gym[atari]).
Fixes #42

Fixed binder dependencies for Pong tutorial.

---

content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md

Removed id markup and fixed item numbering for Pong tutorial.

---

.circleci/config.yml

The CI for generating/previewing/deploying the site is still pretty unreliable even after all of the tweaks and improvements. Unlike e.g. test suites, the tutorials have some computations in them that may require a lot of resources, particularly RAM. From the [circleci docs](https://circleci.com/docs/2.0/executor-types/#available-docker-resource-classes), it looks like the default compute node has 4GB of RAM. Let's see if moving to a node with more resources will help with the stalled/killed tutorial execution.

CI: Fix BLAS threading issue in CI

---

requirements.txt
site/requirements.txt

As noted [here](https://github.com/executablebooks/meta/discussions/285#discussioncomment-518085) it is actually `jupytext` not `jupyter-book` that adds support for .md-based notebooks to jupyter notebook. This changes the requirements to reflect this:
- Removes `jupyter-book` as the dependency is really on `jupytext`
- Moves `jupytext` to the top-level dependencies list as it's necessary both for the site and e.g. binder.

MAINT: Make requirements more precise re: jupytext/jupyterbook.

---

.github/workflows/circleci.yml

Fixes misnamed configuration parameter which is preventing the circleci artifact redirector action (which adds CI summary line with a nice link to the built documentation for PRs) from working correctly.

CI: fix incorrect name in artifact redirector conf.

---

content/pairing.md

I discovered by accident that the [animated gifs in the pairing tutorial](https://numpy.org/numpy-tutorials/content/pairing.html#pair-your-notebook-files-ipynb-and-md) were not showing properly. After some experimentation it appears that if we use html syntax for images, the site is not build correctly - the path for the images ends up wrong. But if we change it to markdown syntax, all works well. So unless we know a fix, I'm suggesting we remove the nice folding html tag for now.

Fixed showing images in the Pairing tutorial

---

content/tutorial-static_equilibrium.md

The site index was built incorrectly because of the headers in the Static Equilibrium tutorial.

Fix for ToC in site index

---

README.md

Add instructions to build the html site to README.

---

README.md

Add link to rendered site at top of README

---

content/tutorial-deep-learning-on-mnist.md
content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md
content/tutorial-ma.md
content/tutorial-svd.md
content/tutorial-x-ray-image-processing.md
site/index.md

I noticed some titles included "Tutorial" and some didn't - it seems like they should be consistent and since this is already the NumPy tutorials repo I think we can remove the word from the title.

Fixed titles for consistency in the index page

---

content/tutorial-deep-learning-on-mnist.md
content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md

For the deep learning frameworks:
- make it more clear that these should be used for any serious deep learning; NumPy isn't the right library beyond learning.
- Remove Swift for TensorFlow (Google abandoned it), add MXNet, and order frameworks in the order we'd want to recommend them.
For the ethics section: this is of pretty fundamental importance, and at least some pointers should be provided in introductory ML/AI
resources so people new to the field at least are aware it's a thing and can explore the topic.
Cc @8bitmp3

Update MNIST tutorial - deep learning frameworks & ethics resources

---

site/index.md

This PR fixes a link in the index page, which currently does not go anywhere because there is no contributing section in index.md. In this branch, the link directs to the contributing page.

Fix link to contributing docs in index.md

---

content/tutorial-x-ray-image-processing.md

I've added my first attempt at alt text for the images in the x-ray image processing tutorial. Thanks to all who participated in the 2021-08-12 alt-text sprint!

Added alt text for the images in the x-ray image processing tutorial

---

content/tutorial-x-ray-image-processing.md

Just something I noticed while reviewing the alt-text changes in the xray image processing tutorial:
The section on loading an "image stack" had a few points that could be improved on. In the first cell in the section, the images are loaded manually rather than programmatically, which is cumbersome and also error prone - for example, there should be 9 images in the final result instead of 8 given the 0-indexed numbering scheme, but img 002 was left out for some reason.
There is also a benchmarking section where appending images in a for-loop is compared to `np.stack` - however; this is an apple-to-oranges comparison because the former included the file IO in the loop whereas the latter did not. I also think that creating the arrays directly from the data rather than explicitly stacking …

Update multi-dimentional array example in xray tutorial

---

content/tutorial-plotting-fractals.md

Minor improvement to the fractals notebook. Modifies the functions so that the boolean mask representing non-diverged values is computed only once per iteration and is reused, which is more efficient.
In principle, this could be modified further to illustrate the use of `out` to save the allocation of a new array in each loop, e.g.
```python
def divergence_rate(mesh, num_iter=10, radius=2):                               
z = mesh.copy()                                                             
diverge_len = np.zeros(mesh.shape)  # Keep tally of the number of iterations
conv_mask = np.ones(mesh.shape, dtype=bool)
for i in range(num_iter):
np.less(np.abs(z), radius, out=conv_mask)                         
diverge_len[conv_mask] += 1 …
```

ENH: compute mask only once per iteration in fractals notebook

---

.circleci/config.yml
environment.yml

This fixes CI but doesn't totally get all of #87 yet.

MAINT: Pin gym[atari] version

---

content/tutorial-nlp-from-scratch.md

Adresses https://github.com/numpy/numpy-tutorials/pull/105#issuecomment-1004524990

Fix image display and clean up for NLP tutorial

---

site/index.md

The original link to the Code of Conduct was bad. This update points to what I believe to be the correct (and stable) URL.

Update Code of Conduct URL

---

requirements.txt

I had to bump the gym requirement to 0.18.3, so that it required a version of pillow > 8.1.1 which added wheels for m1 (https://github.com/python-pillow/Pillow/issues/5093#issuecomment-788459509).

Bump Gym Requirement Version for M1 Support

---

content/tutorial-air-quality-analysis.md

I had made a plot with Matplotlib in an earlier version of the tutorial but didn't end up using it for the final version and I forgot to remove the corresponding lines.

MAINT: Remove Matplotlib as a dependency for AQI tutorial

---

content/text_preprocessing.py
content/tutorial-nlp-from-scratch.md

This should fixes #121. Replace legacy Random Generator (RandomState) with the new Random Generator in the tutorial.

replace examples to random.Generator

---

environment.yml

Jupyter Book has a conda forge package, so it can be installed from there instead of pip, to help with dependency resolution.

Move Jupyter Book to a conda forge requirement

---

.github/workflows/conda.yml
environment.yml
requirements.txt

This PR improves the CI for the project by:
1. Adding jobs to test the `conda`-based workflow
2. Add testing on macOS
The first bullet will ensure that both `conda` and `pip` based workflows are working as expected, and help prevent the dependency specifications from getting out-of-sync.
In principle it'd be great to add windows to the CI as well, but that's currently not possible due to the `gym/atari-py` issue. Once that's solved it should be straightforward to add them.

Improve testing in CI

---

site/conf.py

To fix the warning:
```
WARNING: 'execution_timeout' is deprecated for 'nb_execution_timeout' [mystnb.config]
```
(I'm sorry for the noise, I would like to use this to generate a CI build log that I can use for the purpose of debugging a project of mine).

Updating configitem for newer myst-nb versions

---

environment.yml

For some reason the conda environment isn't working. My suspicion is that it's due to sphinx 5 - AFAIK the executablebooks tooling doesn't support sphinx 5 yet, so I would expect this to have been taken care of by the conda dependency resolver. Pip seems to get this right anyways...
Attempt number 1: manually pin sphinx.

CI Maintenance: fix failing conda build

---

content/tutorial-static_equilibrium.md

Use the best-practice from the [matplotlib gallery 3D examples](https://matplotlib.org/stable/gallery/index.html#d-plotting) for creating 3D axis objects. This gets rid of some warnings that are embedded in the static equilibrium tutorial.

MAINT: Get rid of mpl warnings when creating 3d axes.

---

.github/workflows/notebooks.yml

Closes #51 .
Add a basic `nbval` workflow to the CI, borrowing heavily from @mriduls 's recipe in nx-guides. Currently only smoketests the notebooks with `pytest --nbval-lax`. More rigorous testing (i.e. comparison with saved outputs) can always be explored in followup PRs.
A couple of potential improvements:
1. Find a better way of programmatically excluding certain notebooks from the test suite (see TODO), preferably via `conftest.py` or similar mechanism
2. Add data caching to the workflow
3. Add a `pytest` and `nbval` as testing requirements and update the contributor guide with a quick note on how to run locally.

DEV: Add nbval to CI.

---

.circleci/config.yml
.github/workflows/conda.yml
content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md
environment.yml
requirements.txt

As noted elsewhere the `atari-py` package on which the reinforcement learning tutorial was based was deprecated (#87), and the project that replaces it EULA(s) that need to be reviewed and may no longer be suitable for open source.
We had been using the deprecated `atari-py`, but this has many problems, including the requirement of building wheels locally, and now dependency issues (see #143).
Given all this, I think it's past time that we remove these dependencies, which will necessitate switching the RL notebook to no longer be executable. I took the simplest possible approach to this in this PR. Ultimately, I'd like to start a discussion about what to do with content that is not executable, but I'll leave that for another issue/meeting.

Remove reinforcement learning notebook from executable build

---

content/tutorial-x-ray-image-processing.md

`imageio.imread` is not supported anymore, `imageio.v2.imread` is suggested as a replacement from the module maintainers.

imageio.imread replaced with imageio.v2.imread

---

apt.txt

Minor follow up to #144 - I missed the `apt.txt` which specifies additional dependencies for binder. These are no longer needed now that atari/gym is removed :tada:

MAINT: remove `apt.txt`

---

.github/workflows/notebooks.yml

This does the bare minimum of enabling cron testing, and I don't think will be controversial.  It maybe optimized later to cut back on the number of jobs being run (but maybe that's better done after/in #146 when e.g. developer and/or pre-release version of dependencies are added, etc.)

ENH: Test should run regularly from cron

---

.github/workflows/notebooks.yml
.gitignore
ignore_testing
test_requirements.txt
tox.ini

This should help local testing, etc.
To close #141
It also addresses (potentially), and close https://github.com/numpy/numpy-tutorials/issues/139
TODO (but opening the PR now to see whether this indeed works on GHA not just locally):

ENH: add tox.ini to generize test setup

---

content/tutorial-ma.md

The Polynomial class is recommended over the poly* functional interface for new code.
Creating a draft for now, as the text will need to be updated too!

MAINT: Replace polyfit/polyval with Polynomial class.

---

requirements.txt

I noticed that our builds/deploys were failing with the most recent merges due to pygments lexer warnings. See ipython/ipython#13845 for context.
This should get the build/deploy back working. The pin can be removed presumably whenever IPython 8.7.1 is out.

MAINT: temporary pin to fix lexer.

---

tox.ini

Tox v4 got released in the past week, and indeed cron is failing.
This PR should fix our compatibility with it.

MAINT: fixing compatibility of tox v4

---

content/save-load-arrays.md

0 and 1 are the default start and step respectively, so no need to explicitly include them.

STY: Idiomatic use of arange.

---

content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md
content/tutorial-nlp-from-scratch.md
site/applications.md
site/articles.md
site/index.md

As discussed in the previous documentation meeting, this PR implements the "medium-term" solution to the tutorials that have been added but are not currently executable.
Essentially, this moves the RL and NLP tutorials to a separate category that I called "articles" (naming suggestions welcome) and adds some text that these are not tested. I've also added admonitions soliciting contributions from any one who might be interested in helping to make them fully executable.

MAINT: move non-executable content to its own category.

---

.circleci/config.yml
.github/workflows/notebooks.yml
LICENSE.txt
requirements.txt
site/conf.py

Just some minor CI maintenance. The most important one is updating the circleci deploy image which has been deprecated for a while. Please feel free to push up any other CI maintenance to this PR!

CI: update container images

---

content/tutorial-deep-learning-on-mnist.md

A minor touch-up to the error/accuracy summary in the mnist tutorial. Using fstrings here is more idiomatic (and readable, arguably) than a series of manual string concatenation. In principle `string.Template` could be considered too, but IMO fstrings are good enough!

Use f-strings instead of str concat for train/eval summary.

---

.github/workflows/circleci.yml

Copy of numpy/numpy#23578 to fix static site preview link in CI.
This will only work if CIRCLE_TOKEN is available, and unfortunately we won't know whether this works until after merge.

CI: Add CIRCLE_TOKEN to fix artifact redirection.

---

.github/workflows/ci_tests_run_notebooks.yml

Separating out the windows part from https://github.com/numpy/numpy-tutorials/pull/172, based on the review comment.

CI: adding windows testing to CI

---

.github/workflows/ci_tests_run_notebooks.yml
environment.yml
requirements.txt
tox.ini

This PR adds the following to the matrix:
- python 3.11 testing
- windows testing, that close #142
Edit: opinions about versions to support:
- Python: at least the versions that the current, latest release of numpy supports. Currently, that's py3.8+
- numpy: releases from the last 2 years to follow NEP-29 logic? I'm not sure, it maybe possible to support just the last year of releases?
- other dependencies: releases from the last 2 years to follow NEP-29 logic? I suspect this is the point that may cause the most pain points.

CI: Update/extend CI matrix

---

content/tutorial-x-ray-image-processing.md
environment.yml
requirements.txt

Fixes #179.
Ultimately I'd like to replace `imageio.mimwrite` altogether with an embedded html animation generated directly by matplotlib, but I'm not 100% sure how to accomplish that (there are related issues on the executablebooks trackers that have some ideas where to start).

MAINT: rm imageio pin and switch to durations kwarg.

---

environment.yml
site/requirements.txt

Removes explicit pin from sphinx. IIRC, the one in `environment.yml` might be necessary because the dependency management of at least one of the executablebooks packages is not reliable on conda-forge specifically. Nevertheless, the `requirements` pin should be unnecessary, and I think we should endeavor to use the latest version of sphinx that we can support!
If the conda job fails, I'll re-add the `environment` pin.

MAINT: Unpin sphinx.

---

content/tutorial-deep-learning-on-mnist.md

Fixes #188 
Also refactors the metric computation/reporting with coding best-practices:
- Gets rid of unnecessary explicit `float` conversions for denominators
- Use dicts to more tightly couple the metric labels and their values, reducing the total number of variables to keep track of
- Replace list comprehensions with vectorization

Fix bug and improve computation / display of metrics for MNIST tutorial

---

content/mooreslaw-tutorial.md
environment.yml
requirements.txt
tox.ini

This replaces the usage of `statsmodels` in the Moore's law tutorial with numpy.polynomial.Polynomial.fit, as this is a nice opportunity to demonstrate the Polynomial package fitting. This has the added benefit of reducing the dependency footprint and hopefully working around the latest CI failures for Python 3.11.
One downside of switching from `sm.OLS` to `Polynomial.fit` is the latter does not return the covariance matrix. IMO the benefits of demonstrating polynomial fitting with NumPy outweigh this, and methods for estimating the standard error of model parameters can be added back in a follow-up PR.
Closes #157

ENH: Use numpy.polynomial for linear fit instead of statsmodels

---

.github/workflows/ci_tests_run_notebooks.yml
content/tutorial-ma.md
tox.ini

I'll also use this PR to fix https://github.com/numpy/numpy-tutorials/issues/190 
I'm happy to separate the PR into two, one to bump the minimum versions following SPEC0 and the other to update and fix the devdeps job

MAINT: update minimum required versions and CI maintanance

---

.github/workflows/ci_tests_run_notebooks.yml

Adding this job as a safeguard for the reasonably rare case when an RC is out for a dependency (e.g. we do test now for numpy 1.26.x and 2.1.dev, but not for the 2.0RC releases, while in theory, those may cause some issues).
We may want to consider swapping this job in the place of the one with the latest releases (as they will be practically identical when there are no RC releases for any of the dependencies).
To close #206

CI: adding predeps job

---

content/tutorial-svd.md

fix a typo in a link to Wikipedia article

DOC: Update tutorial-svd.md fix a typo

---

environment.yml

I think binder looks at env.yaml not at requirements.txt maybe that's the reason that binder don't have jupytext installed

Add Jupytext requirement for binder.

---

site/conf.py

There is a known issue with the "edit-this-page" feature of the theme related to the fact that the site relies on symlinks that violates the theme's expectations re: paths to content. See #89 for details.
This PR simply disables the feature for now to prevent duplicate issues.
Closes #231 #229

Turn off edit-this-page button.

---

content/mooreslaw-tutorial.md

The original link to the PDF is broken. Not sure what was in the original content linked out to,
but this updated content link is from the same site so may be a good replacement.

Fix broken link

---

content/tutorial-deep-learning-on-mnist.md

Update the link to linear algebra tutorial.
New link: https://numpy.org/numpy-tutorials/content/tutorial-svd.html
Old link does not work.
https://numpy.org/doc/stable/user/tutorial-svd.html

DOC: Update the link to linear algebra tutorial

---

content/tutorial-nlp-from-scratch.md

Update another link to linear algebra tutorial.
Related to PR #243. 
New link: https://numpy.org/numpy-tutorials/content/tutorial-svd.html
Old link does not work.
https://numpy.org/doc/stable/user/tutorial-svd.html

DOC: Update another link to linear algebra tutorial

---

content/tutorial-deep-reinforcement-learning-with-pong-from-pixels.md

Update two links in deep reinforcement learning tutorial.
The first one is a Wikipedia page to the Pong video game.
https://en.wikipedia.org/wiki/Pong
The second one is the OpenAI Gym website, which has been moved.
https://github.com/openai/gym

DOC: Update two links in deep reinforcement learning tutorial

---

content/tutorial-deep-learning-on-mnist.md

Update the MNIST data link.
The original link from Yann LeCun's website has removed the dataset:
http://yann.lecun.com/exdb/mnist/
Let's use the Kaggle version instead:
https://www.kaggle.com/datasets/hojjatk/mnist-dataset

DOC: Update the MNIST data link

---

content/tutorial-deep-learning-on-mnist.md

Closes #254 using @melissawm and @bsipocz 's idea.
I tried simply swapping out the host URLs from github -> ossci and it seems to work. No idea about rate limits on the bucket but as @bsipocz noted it should at least be better than the status quo.

MNT: Point mnist data download to ossci server.

---

content/tutorial-svd.md

This PR re-words a paragraph on shape and axes of an image.
closes #259

Slightly improve explanation of image shape in svd-tutorial.md
